//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSCT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malzeme
    {
        public int MalzemeKodu { get; set; }
        public string MalzemeAdi { get; set; }
        public string MalzemeTuru { get; set; }
        public double VergiOrani { get; set; }
        public string StoklamaOlcuBirimi { get; set; }
    }
}
