//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSCT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSCTEntities : DbContext
    {
        public MSCTEntities()
            : base("name=MSCTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Malzeme> Malzemes { get; set; }
        public virtual DbSet<Musteri> Musteris { get; set; }
        public virtual DbSet<SiparisBaslik> SiparisBasliks { get; set; }
        public virtual DbSet<SiparisKalem> SiparisKalems { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
