//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSCT
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisKalem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiparisKalem()
        {
            this.SiparisBasliks = new HashSet<SiparisBaslik>();
        }
    
        public int KalemNo { get; set; }
        public int MalzemeKodu { get; set; }
        public double Miktar { get; set; }
        public string StoklamaÖlçüBirimi { get; set; }
        public double BirimFiyat { get; set; }
        public double VergiTutarı { get; set; }
        public double NetTutar { get; set; }
        public string MalzemeAdı { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisBaslik> SiparisBasliks { get; set; }
    }
}
