//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSCT
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisBaslik
    {
        public int SiparisNo { get; set; }
        public string SiparisTuru { get; set; }
        public string TeslimTarihi { get; set; }
        public string Müşteri { get; set; }
        public double ToplamTutar { get; set; }
        public string ParaBirimi { get; set; }
        public int KalemNo { get; set; }
    
        public virtual SiparisKalem SiparisKalem { get; set; }
    }
}
